### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by ORelio** [jwilson8767/shp2zipwin#1]
Hi,

I have identified potential issues in [install.bat](https://github.com/jwilson8767/shp2zipwin/blob/master/install.bat):
 - the command assumes Powershell's [execution policy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy) has been already set to allow script files
 - `[default=false]` means _optional parameter that if missing is considered to be `false`_
 - the script does not create `%appdata%\\ShellExtensions` which is not there by default
 - the command should contain the full path to `"%appdata%\\ShellExtensions\shp2zip.ps1"`

**Comment by jwilson8767** [comment]
Wow, totally didn't see this issue until just now! Thanks for feedback and I will correct this asap!

**Comment by ORelio** [comment]
No worries, it is your project after all 😉

**Comment by jwilson8767** [comment]
I just super appreciate you taking the time to review and give feedback and didn't want you to feel like your time was a waste! I've implemented the changes you suggested and (I think) set the execution mode properly for those scripts (assuming I don't have to do something at the system-wide level).

**Comment by ORelio** [comment]
I think setting the execution mode as command line argument is the most convenient way. I did the same [in this script](https://github.com/ORelio/Spotlight-Downloader/blob/master/Scripts/update-lockscreen.bat#L17).
